/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bt;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ntykn
 */
public class DSNhanvien extends javax.swing.JFrame {

    private static DefaultTableModel getModel() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * Creates new form DSNhanvien
     */
    public DSNhanvien() {
        initComponents();
       
        try {
               Connection  conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/qlks","root","");
               PreparedStatement st = conn.prepareStatement("select * from nhanvien");
               ResultSet rs = st.executeQuery();
               DefaultTableModel model = (DefaultTableModel) dsNv.getModel();
               while(rs.next()){
                   Object objList[] = {rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(5)};
                   model.addRow(objList);
               }
               model.fireTableDataChanged();     
            } catch (SQLException ex) {
                Logger.getLogger(DSPhong.class.getName()).log(Level.SEVERE, null, ex);
            }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        dsNv = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtma = new javax.swing.JTextField();
        txtten = new javax.swing.JTextField();
        txtdc = new javax.swing.JTextField();
        txtsdt = new javax.swing.JTextField();
        txtchucvu = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btXoa = new javax.swing.JButton();
        BtSua = new javax.swing.JButton();
        BtThem = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        btsearch = new javax.swing.JButton();
        txtSearch = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("DANH SÁCH NHÂN VIÊN");

        dsNv.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Ma Nv", "Ten Nv", "Dia chi", "Sdt", "Chuc vu"
            }
        ));
        dsNv.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dsNvMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(dsNv);

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));

        jLabel2.setText("Ma Nv:");

        txtten.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttenActionPerformed(evt);
            }
        });

        jLabel3.setText("Ten Nv:");

        jLabel4.setText("Dia chi:");

        jLabel5.setText("Sdt:");

        jLabel6.setText("Chuc vu:");

        btXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-xbox-x-25.png"))); // NOI18N
        btXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btXoaActionPerformed(evt);
            }
        });

        BtSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-pen-25.png"))); // NOI18N
        BtSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtSuaActionPerformed(evt);
            }
        });

        BtThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-plus-+-25.png"))); // NOI18N
        BtThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtThemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addComponent(jLabel3)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(3, 3, 3)))
                        .addGap(43, 43, 43)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtma, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtchucvu, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                                .addComponent(txtsdt)
                                .addComponent(txtdc)
                                .addComponent(txtten))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btXoa)
                        .addGap(18, 18, 18)
                        .addComponent(BtThem)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BtSua)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtten, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtdc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtsdt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtchucvu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btXoa)
                        .addComponent(BtSua))
                    .addComponent(BtThem))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-back-arrow-30.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btsearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/search.png"))); // NOI18N
        btsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btsearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(149, 149, 149)
                                .addComponent(jLabel1)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txttenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttenActionPerformed

    private void btXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btXoaActionPerformed
        // TODO add your handling code here:\
        String sqlDelete = "DELETE FROM nhanvien where idnhanvien=?";
        
        
        int ret = JOptionPane.showConfirmDialog(this, "Ban co muon xoa nhan vien nay?", "Confirm", JOptionPane.YES_NO_OPTION);
        if(ret != JOptionPane.YES_OPTION) {
         return;
        } 
        try {
          DefaultTableModel model = DSNhanvien.getModel();
          Connection  c = DriverManager.getConnection("jdbc:mysql://localhost:3306/qlks","root","");
          PreparedStatement pt = c.prepareStatement(sqlDelete);
          pt.setString(1, dsNv.getValueAt(dsNv.getSelectedRow(), 0).toString());
          pt.executeUpdate();
          JOptionPane.showMessageDialog(this, "Da xoa nhan vien");
         
          c.close();
          pt.close();
        } catch (Exception ex) {
            Logger.getLogger(DSPhong.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btXoaActionPerformed

    private void BtThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtThemActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) dsNv.getModel();
        int ret = JOptionPane.showConfirmDialog(this, "Ban co muon luu khong?", "Dong y", JOptionPane.YES_NO_OPTION);
        String insert = "insert into nhanvien (idnhanvien,tennv,diachi,sdt,chucvu) values(?,?,?,?,?)";
        System.out.println(insert);
        Connection conn = null;
        PreparedStatement ps = null;
        try {
         conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/qlks","root","");
         ps = conn.prepareStatement(insert);
         ps.setString(1, txtma.getText());
         
         ps.setString(2,txtten.getText());
         ps.setString(3,txtdc.getText());
         ps.setString(4,txtsdt.getText());
         ps.setString(5,txtchucvu.getText());
        
          ps.executeUpdate();
         if (ret != -1) {   
           
         }
        } catch (Exception e) {
          e.printStackTrace();
        } finally {
          try {
           if (conn != null) {
            conn.close();
           }
           if (ps != null) {
            ps.close();
           }
          } catch (Exception ex2) {
           ex2.printStackTrace();
          }
       }
    }//GEN-LAST:event_BtThemActionPerformed

    private void BtSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtSuaActionPerformed
        // TODO add your handling code here:
        String sqlUpdate = "UPDATE nhanvien SET tennv=?,diachi=?,sdt=?,chucvu=? Where idnhanvien=?";
       
        try {
            JOptionPane.showMessageDialog(null,"Sua thanh cong!","Xac Nhan",1);
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/qlks","root","");
            PreparedStatement pt = conn.prepareStatement(sqlUpdate);
            pt.setString(8, txtsdt.getText());
            pt.setString(1, txtten.getText());
            pt.setString(2, txtdc.getText());
            pt.setString(3, txtsdt.getText());
            pt.setString(4, txtchucvu.getText());
            
           pt.executeUpdate();
           
           
           
           conn.close();
           pt.close();
        } catch (Exception ex) {
            Logger.getLogger(DSPhong.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BtSuaActionPerformed

    private void dsNvMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dsNvMouseClicked
        // TODO add your handling code here:
        int row = dsNv.getSelectedRow();
        
        String idphong =dsNv.getValueAt(row, 0).toString();
        String Ten =dsNv.getValueAt(row, 1).toString();
        String DiaChi =dsNv.getValueAt(row, 2).toString();
        String SDT =dsNv.getValueAt(row, 3).toString();
        String Chucvu =dsNv.getValueAt(row, 4).toString();
       
        
        txtma.setText(idphong);
        txtten.setText(Ten);
        txtdc.setText(DiaChi);
        txtsdt.setText(SDT);
        txtchucvu.setText(Chucvu);
        
    }//GEN-LAST:event_dsNvMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new Menu().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btsearchActionPerformed
        // TODO add your handling code here:
        Connection conn = null;
        Statement st = null;
        ResultSet rs = null;
        try {
                conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/qlks","root","");
               st = conn.createStatement();
               String sql = "select * from nhanvien";
               if (txtSearch.getText().length() > 0) {
                    sql = sql + " where tennv like '%" + txtSearch.getText() + "%'";}
                rs = st.executeQuery(sql);
               DefaultTableModel model = (DefaultTableModel) dsNv.getModel();
                Vector data = null;
                model.setRowCount(0);
           
                if (rs.isBeforeFirst() == false) {
                 JOptionPane.showMessageDialog(this, "Khong tim thay nhan vien!");
                 return;
                }
                // Trong khi chưa hết dữ liệu
                while (rs.next()) {
                  data = new Vector();
                  data.add(rs.getInt("idnhanvien"));
                  data.add(rs.getString("tennv"));
                  data.add(rs.getString("diachi"));
                  data.add(rs.getString("sdt"));
                  data.add(rs.getString("chucvu"));
                  
                  // Thêm một dòng vào table model
                  model.addRow(data);
                }
                dsNv.setModel(model); // Thêm dữ liệu vào table
                
                } catch (Exception e) {
                    e.printStackTrace();
                  } finally {
                    try {
                      if (conn != null) {
                        conn.close();
                      }
                      if (st != null) {
                       st.close();
                      }
                      if (rs != null) {
                       rs.close();
                      }
               
            } catch (SQLException ex) {
            }
    }                      
    }//GEN-LAST:event_btsearchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DSNhanvien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DSNhanvien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DSNhanvien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DSNhanvien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DSNhanvien().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtSua;
    private javax.swing.JButton BtThem;
    private javax.swing.JButton btXoa;
    private javax.swing.JButton btsearch;
    private javax.swing.JTable dsNv;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtchucvu;
    private javax.swing.JTextField txtdc;
    private javax.swing.JTextField txtma;
    private javax.swing.JTextField txtsdt;
    private javax.swing.JTextField txtten;
    // End of variables declaration//GEN-END:variables
}
